store:
  message: "§rDonate to the server at §bhttps://novaserver.xyz/store"
  link: "https://novaserver.xyz/store"
  hover: "§fClick to view the donation store."
  enabled: true
discord:
  message: "§rJoin our Discord server: §bdiscord.gg/m52kfmbqAm"
  link: "https://discord.gg/m52kfmbqAm"
  hover: "§fClick to use the Discord invite."
  enabled: true
map:
  message: "§rView the map at §bhttps://map.novaserver.xyz"
  link: "https://map.novaserver.xyz"
  hover: "§fClick to view the map."
  enabled: true

report:
  enabled: true
  webhook-enabled: false
  webhook-url: ""
  avatar-url: "https://crafatar.com/avatars/%s.png"
  message: "§cReported §f%s §cto the admins!"
  admin-message:
    - "§f%name% §cwas reported by §e%reporter%"
    - "§cFor the reason §f%reason%"

hub:
  enabled: true
  server-name: 'lobby'
  message: "§bSending you to the §chub§b..."

proxy-cmd:
  enabled: false

# Have players wait in limbo until their resource pack is loaded
resource-pack-limbo:
  enabled: false
  limbo-server: "limbo"