privacy:
  message: "§d§lPrivacy: §rRead our privacy policy: §bhttps://novaserver.xyz/privacy"
  link: "https://novaserver.xyz/privacy"
  hover: "§fClick to read the privacy policy."
store:
  message: "§3§lStore: §rDonate to the server at §bhttps://novaserver.xyz/store"
  link: "https://novaserver.xyz/store"
  hover: "§fClick to view the donation store."
discord:
  message: "§b§lDiscord: §rJoin our Discord server: §bdiscord.gg/m52kfmbqAm"
  link: "https://discord.gg/m52kfmbqAm"
  hover: "§fClick to use the Discord invite."
map:
  message: "§b§lMap: §rView the map at §bhttps://map.novaserver.xyz"
  link: "https://map.novaserver.xyz"
  hover: "§fClick to view the map."

report:
  webhook-enabled: false
  webhook-url: ""
  avatar-url: "https://crafatar.com/avatars/%s.png"
  message: "§cReported §f%s §cto the admins!"
  admin-message:
    - "§f%name% §cwas reported by §e%reporter%"
    - "§cFor the reason §f%reason%"

hub:
  server-name: 'lobby'
  message: "§bSending you to the §chub§b..."
