name: Gravity
version: 1.0
author: Nova
website: https://github.com/NovaMC
main: xyz.novaserver.gravity.Gravity
api-version: 1.16

commands:
  privacy:
    description: "Read the server's privacy policy."
  store:
    aliases: donate
    description: "View the donation store."
  ping:
    description: "View your ping to the server."
  discord:
    description: "View the Discord server invite."
  map:
    description: "View the server's dynmap."
  hub:
    aliases: lobby
    description: "Takes you back to the lobby."
  report:
    description: "Reports a player to the admins."

permissions:
  gravity.reports.notify:
    description: "Allows staff to be sent reports in-game."
    default: op
  gravity.reports.report:
    description: "Report players to staff with /report"
    default: true
  gravity.admin:
    description: "Allows access to admin commands like reloading."
    default: op